[package]
name = "rust-hello-world"
version = "0.1.0"
edition = "2021"
description = "A simple Hello World program written in Rust"
homepage = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
